// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Go-000/Week04/internal/myservice/biz"
	"Go-000/Week04/internal/myservice/data"
	_ "github.com/go-kratos/kratos/v2/encoding/json"
	_ "github.com/go-kratos/kratos/v2/encoding/proto"
)

// Injectors from wire.go:

func InitializeUserUsecase() (*biz.UserUsecase, func(), error) {
	connectionOpt := data.DefaultConnectionOpt()
	db, cleanup, err := data.NewDb(connectionOpt)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(db)
	userUsecase := biz.NewUserUsecase(userRepo)
	return userUsecase, func() {
		cleanup()
	}, nil
}
